"""Writes a small calibration dataset (HF `datasets` folder with a `text` column)
from the solar workload so INT4-AWQ scaling factors are tuned on the prompts
this platform actually serves."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from solarbench.workload.generator import generate  # noqa: E402


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    ap.add_argument("--n", type=int, default=512)
    a = ap.parse_args()
    out = Path(a.out)
    out.mkdir(parents=True, exist_ok=True)
    with (out / "calib.jsonl").open("w") as f:
        for r in generate(seed=2026, n=a.n):
            f.write(json.dumps({"text": "\n\n".join(m["content"] for m in r["messages"])}) + "\n")
    # datasets.load_dataset("json", data_files=...) is how quantize.py reads a local folder; leave a loader hint.
    (out / "README.md").write_text("Calibration texts generated by solarbench (synthetic solar O&M prompts).\n")
    print(f"wrote {a.n} calibration texts to {out}")


if __name__ == "__main__":
    main()
