"""Turns results/*/summary.json into docs/results.md and docs/plots/*.png.
Markdown output is deterministic (sorted, fixed formatting) so CI can check
that the committed report matches the committed results."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

HEADLINE_COLS = [
    ("stack", "Stack"),
    ("mode_load", "Load"),
    ("req_per_s", "req/s"),
    ("output_tok_per_s", "out tok/s"),
    ("ttft_p50", "TTFT p50 s"),
    ("ttft_p99", "TTFT p99 s"),
    ("tpot_p50", "TPOT p50 ms"),
    ("goodput", "goodput req/s"),
    ("usd_per_m_output", "$/M out tok"),
    ("peak_mem", "peak GPU MiB"),
]


def load_runs(results_dir: Path) -> list[dict[str, Any]]:
    runs = []
    for d in sorted(results_dir.iterdir()):
        s = d / "summary.json"
        if not s.exists():
            continue
        summary = json.loads(s.read_text())
        cfg = json.loads((d / "config.json").read_text()) if (d / "config.json").exists() else {}
        quality = json.loads((d / "quality.json").read_text()) if (d / "quality.json").exists() else None
        runs.append({"dir": d.name, "summary": summary, "config": cfg, "quality": quality})
    return runs


def _f(x: Any, nd: int = 2) -> str:
    if x is None:
        return "-"
    if isinstance(x, float):
        return f"{x:.{nd}f}"
    return str(x)


def _row(run: dict[str, Any]) -> dict[str, str]:
    s, c = run["summary"], run["config"]
    load = f"c={c.get('concurrency')}" if s.get("mode") == "closed" else f"{c.get('rps')} rps"
    cost = s.get("cost") or {}
    return {
        "stack": s.get("stack", "?"),
        "mode_load": load,
        "req_per_s": _f(s.get("req_per_s")),
        "output_tok_per_s": _f(s.get("output_tok_per_s"), 0),
        "ttft_p50": _f(s["ttft_s"].get("p50"), 3),
        "ttft_p99": _f(s["ttft_s"].get("p99"), 3),
        "tpot_p50": _f((s["tpot_s"].get("p50") or 0) * 1000, 1) if s["tpot_s"].get("p50") is not None else "-",
        "goodput": _f(s["slo"].get("goodput_req_per_s")),
        "usd_per_m_output": _f(cost.get("usd_per_m_output_tokens")),
        "peak_mem": _f(s.get("engine_peaks", {}).get("peak_gpu_mem_used_mib"), 0),
    }


def table(rows: list[dict[str, str]], cols: list[tuple[str, str]]) -> str:
    head = "| " + " | ".join(h for _, h in cols) + " |"
    sep = "|" + "|".join("---" for _ in cols) + "|"
    body = ["| " + " | ".join(r[k] for k, _ in cols) + " |" for r in rows]
    return "\n".join([head, sep, *body])


def render(runs: list[dict[str, Any]]) -> str:
    out = ["# Benchmark results", "", "Generated by `solarbench report` from the `results/` directory. Do not edit by hand.", ""]
    if not runs:
        out.append("_No runs yet._")
        return "\n".join(out) + "\n"
    out += ["## Headline", "", table([_row(r) for r in runs], HEADLINE_COLS), ""]
    out += ["## Per task class", ""]
    task_cols = [
        ("stack", "Stack"),
        ("mode_load", "Load"),
        ("task", "Task"),
        ("n", "n"),
        ("in_tok", "prompt tok"),
        ("out_tok", "out tok"),
        ("ttft_p50", "TTFT p50 s"),
        ("ttft_p99", "TTFT p99 s"),
        ("tpot_p50", "TPOT p50 ms"),
        ("e2e_p50", "E2E p50 s"),
    ]
    rows = []
    for r in runs:
        base = _row(r)
        for task, t in sorted(r["summary"].get("by_task", {}).items()):
            rows.append(
                {
                    "stack": base["stack"],
                    "mode_load": base["mode_load"],
                    "task": task,
                    "n": str(t["n"]),
                    "in_tok": _f(t.get("prompt_tokens_mean"), 0),
                    "out_tok": _f(t.get("completion_tokens_mean"), 0),
                    "ttft_p50": _f(t["ttft_s"].get("p50"), 3),
                    "ttft_p99": _f(t["ttft_s"].get("p99"), 3),
                    "tpot_p50": _f((t["tpot_s"].get("p50") or 0) * 1000, 1) if t["tpot_s"].get("p50") is not None else "-",
                    "e2e_p50": _f(t["e2e_s"].get("p50"), 2),
                }
            )
    out += [table(rows, task_cols), ""]
    q_runs = [r for r in runs if r["quality"]]
    if q_runs:
        out += ["## Quality (structured tasks)", ""]
        qcols = [("stack", "Stack"), ("task", "Task"), ("n", "n"), ("valid", "valid JSON"), ("schema", "schema valid"), ("score", "field score")]
        qrows = []
        for r in q_runs:
            for task, q in sorted(r["quality"].items()):
                qrows.append(
                    {
                        "stack": r["summary"].get("stack", "?"),
                        "task": task,
                        "n": str(q["n"]),
                        "valid": _f(q["valid_json_rate"]),
                        "schema": _f(q["schema_valid_rate"]),
                        "score": _f(q["score"]),
                    }
                )
        out += [table(qrows, qcols), ""]
    out += ["## Runs", ""]
    for r in runs:
        c = r["config"]
        out.append(
            f"- `{r['dir']}`: {c.get('stack')} on {c.get('instance_type') or '?'} at ${_f(c.get('price_per_hour'))}/h, "
            f"model `{c.get('model')}`, dataset `{c.get('dataset')}`, git `{c.get('git_sha')}`. {c.get('notes', '')}".rstrip()
        )
    return "\n".join(out) + "\n"


def plots(runs: list[dict[str, Any]], plots_dir: Path) -> list[Path]:
    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plots_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    stacks = sorted({r["summary"].get("stack") for r in runs})
    # goodput / throughput vs offered load, one line per stack (open-loop runs)
    fig, ax = plt.subplots(1, 2, figsize=(11, 4))
    for st in stacks:
        rs = sorted((r for r in runs if r["summary"].get("stack") == st and r["summary"].get("mode") == "open"), key=lambda r: r["summary"]["load"])
        if not rs:
            continue
        x = [r["summary"]["load"] for r in rs]
        ax[0].plot(x, [r["summary"]["output_tok_per_s"] for r in rs], marker="o", label=st)
        ax[1].plot(x, [r["summary"]["ttft_s"]["p99"] or 0 for r in rs], marker="o", label=st)
    ax[0].set_xlabel("offered load (req/s)")
    ax[0].set_ylabel("output tok/s")
    ax[0].set_title("Throughput vs load")
    ax[1].set_xlabel("offered load (req/s)")
    ax[1].set_ylabel("TTFT p99 (s)")
    ax[1].set_title("Tail latency vs load")
    for a in ax:
        a.grid(alpha=0.3)
        a.legend()
    p = plots_dir / "load_curves.png"
    fig.tight_layout()
    fig.savefig(p, dpi=120)
    plt.close(fig)
    written.append(p)
    # cost vs quality frontier
    pts = [
        (r["summary"]["cost"]["usd_per_m_output_tokens"], sum(q["score"] for q in r["quality"].values()) / len(r["quality"]), r["summary"]["stack"])
        for r in runs
        if r.get("quality") and r["summary"].get("cost") and r["summary"]["cost"].get("usd_per_m_output_tokens")
    ]
    if pts:
        fig, ax1 = plt.subplots(figsize=(6, 4))
        for x, y, st in pts:
            ax1.scatter(x, y)
            ax1.annotate(st, (x, y), fontsize=8)
        ax1.set_xlabel("$ per M output tokens")
        ax1.set_ylabel("mean structured-task score")
        ax1.set_title("Quality vs cost")
        ax1.grid(alpha=0.3)
        p = plots_dir / "quality_vs_cost.png"
        fig.tight_layout()
        fig.savefig(p, dpi=120)
        plt.close(fig)
        written.append(p)
    return written
